### ISSUE TITLE
Where is documentation?

### ISSUE THREAD

**Issue by voronind** [odoo/upgrade-util#37]

**Comment by wm-cortex** [comment]
https://www.odoo.com/documentation/17.0/developer/reference/upgrade_utils.html?highlight=upgrade%20util

**Comment by Feyensv** [comment]
As said by @wm-cortex, the doc can be found in the [official odoo documentation](https://www.odoo.com/documentation/master/developer/reference/upgrades/upgrade_utils.html)
Furthermore, it has been significantly improved recently with #66.

**Comment by voronind** [comment]
May be add link in repo docs?

**Comment by aj-fuentes** [comment]
@voronind here they are https://www.odoo.com/documentation/17.0/developer/reference/upgrades/upgrade_utils.html

More would be added incrementally.
