### ISSUE TITLE
[BUG] don't use tmp file when the migration is very long

### ISSUE THREAD

**Issue by fmdl** [odoo/upgrade-util#63]
Steps to reproduce:
On server start a migration with python <(curl -s https://upgrade.odoo.com/upgrade) test -d 
some file is create in tmp
--> if the migration take lot of time (24 hour), files in tmp are delete by the system (or if server are rebooted). without file it is not possible to resume the migration.

patch : use a normal directory
```python
def gettempdir():
    dir = os.path.join(os.path.expanduser('~'), '.upgrade')
    if not os.path.exists(dir):
        os.makedirs(dir)
    return dir

tempfile.gettempdir = gettempdir
```

**Comment by aj-fuentes** [comment]
The behavior is intended. 

Solution:
```sh
$ mkdir ~/.upgrade
$ TMP=~/.upgrade python <(curl -s https://upgrade.odoo.com/upgrade) test -d
```
https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir
